### ISSUE TITLE
Unhandled Exception on Application Startup

### ISSUE THREAD

**Issue by syntax-tm** [syntax-tm/SteamAchievementManager#6]
Hello, hope it's fine for me to comment here. I've been able to compile it fine even before the update 2 days ago, after installing .Net 7. I tried with the latest update and without, but I have been unable to run the exe successfully. It always starts up with an error along the lines of:

"An error occured on application startup. Line "14" and line position "14". Provide value on 'DevExpress.Mvvm.UI.ViewModelSourceExtension' threw an exception.

![image](https://github.com/syntax-tm/SteamAchievementManager/assets/13744383/acd1093c-7229-4486-a70e-8b3eb09a6019)

_Originally posted by @BasedOnPixels in https://github.com/syntax-tm/SteamAchievementManager/issues/5#issuecomment-1665650925_

**Comment by BasedOnPixels** [comment]
I will respond here for this issue

<details><summary>From the log.txt (click to expand)</summary>



``` 2023-08-05 01:25:14,177 [1] ERROR App [(null)] - An error occurred on application startup. Zeilennummer "14" und Zeilenposition "14" von "Die Angabe eines Werts für "DevExpress.Mvvm.UI.ViewModelSourceExtension" führte zu einer Ausnahme.".
System.Windows.Markup.XamlParseException: Zeilennummer "14" und Zeilenposition "14" von "Die Angabe eines Werts für "DevExpress.Mvvm.UI.ViewModelSourceExtension" führte zu einer Ausnahme.".
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'original')
   at SAM.Core.LocationHelper.GetShortLocation(String original) in D:\SteamAchievementManager-master\SAM.Core\Common\Helpers\LocationHelper.cs:line 24
   at SAM.Core.SteamUser.RefreshProfile() in D:\SteamAchievementManager-master\SAM.Core\Models\SteamUser.cs:line 75
   at SAM.Core.SteamUser..ctor() in D:\SteamAchievementManager-master\SAM.Core\Models\SteamUser.cs:line 38
   at lambda_method2(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\SteamAchievementManager-master\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\SteamAchievementManager-master\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_f180dc22_6dac_44c8_b424_2c10d24f962d..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\SteamAchievementManager-master\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\SteamAchievementManager-master\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\SteamAchievementManager-master\SAM\App.xaml.cs:line 41
``` 
</details>

<details><summary>Errors.txt (click to expand)</summary>



```
2023-08-04 15:38:37,810 [1] FATAL App [(null)] - No app ID argument was supplied. Application will now exit...
2023-08-04 15:38:45,112 [1] ERROR App [(null)] - An error occurred on application startup. Zeilennummer "14" und Zeilenposition "14" von "Die Angabe eines Werts für "DevExpress.Mvvm.UI.ViewModelSourceExtension" führte zu einer Ausnahme.".
System.Windows.Markup.XamlParseException: Zeilennummer "14" und Zeilenposition "14" von "Die Angabe eines Werts für "DevExpress.Mvvm.UI.ViewModelSourceExtension" führte zu einer Ausnahme.".
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'original')
   at SAM.Core.LocationHelper.GetShortLocation(String original) in D:\SteamAchievementManager-master\SAM.Core\Common\Helpers\LocationHelper.cs:line 24
   at SAM.Core.SteamUser.RefreshProfile() in D:\SteamAchievementManager-master\SAM.Core\Models\SteamUser.cs:line 75
   at SAM.Core.SteamUser..ctor() in D:\SteamAchievementManager-master\SAM.Core\Models\SteamUser.cs:line 38
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\SteamAchievementManager-master\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\SteamAchievementManager-master\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_61c9cd7e_f39c_447c_8694_a8ede8d95c39..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\SteamAchievementManager-master\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\SteamAchievementManager-master\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\SteamAchievementManager-master\SAM\App.xaml.cs:line 41
``` 
</details>

**Comment by syntax-tm** [comment]
@BasedOnPixels I just pushed a change that should fix that. It looks like the problem was your Steam profile not having a location set. I didn't realize it was possible to not have one set so I just added a check for that. Let me know if this works or not when you get the chance. Thanks!

**Comment by BasedOnPixels** [comment]
It seems to work fine now, thanks. It takes a very long time to load when you have over 1000 games though. Also the logs are being spammed with too many requests errors, all with different App IDs

<details><summary>Log.txt (click to expand)</summary>


``` 
2023-08-04 15:54:57,878 [6] ERROR SteamApp [(null)] - An error occurred attempting to load the store info for app 260160. One or more errors occurred. (Response status code does not indicate success: 429 (Too Many Requests).)
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 429 (Too Many Requests).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SAM.Core.SteamworksManager.GetAppInfo(UInt32 id, Boolean loadDlc) in D:\Users\Jack\Desktop\Steam tools\Steam Achievement Manager Mod\SteamAchievementManager-master\SAM.Core\API\Steamworks\SteamworksManager.cs:line 144
   at SAM.Core.SteamApp.LoadStoreInfo() in D:\Users\Jack\Desktop\Steam tools\Steam Achievement Manager Mod\SteamAchievementManager-master\SAM.Core\Models\SteamApp.cs:line 176
``` 
</details>

<details><summary>Errors.txt (click to expand)</summary>


```
2023-08-06 11:33:30,496 [7] ERROR SteamApp [(null)] - An error occurred attempting to load the store info for app 220050. One or more errors occurred. (Response status code does not indicate success: 429 (Too Many Requests).)
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 429 (Too Many Requests).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SAM.Core.SteamworksManager.GetAppInfo(UInt32 id, Boolean loadDlc) in D:\SteamAchievementManager-master\SAM.Core\API\Steamworks\SteamworksManager.cs:line 144
   at SAM.Core.SteamApp.LoadStoreInfo() in D:\SteamAchievementManager-master\SAM.Core\Models\SteamApp.cs:line 176
```
</details>

(Several MB of the same error messages)
![image](https://github.com/syntax-tm/SteamAchievementManager/assets/13744383/c3a90b99-0280-4324-a388-2ec9c0ec0a20)

**Comment by SandeMC** [comment]
The same error still occurs to me with up-to-date build. 
<details>
<summary>errors.txt:</summary>

```
2023-08-06 20:32:58,804 [1] ERROR App [(null)] - An error occurred on application startup. "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
System.Windows.Markup.XamlParseException: "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '0.0' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Decimal.Parse(String s)
   at SAM.Core.Extensions.XmlExtensions.GetValueAsDecimal(XmlNode node, String path) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Common\Extensions\XmlExtensions.cs:line 22
   at SAM.Core.SteamUser.RefreshProfile() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 85
   at SAM.Core.SteamUser..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 38
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_27ad6281_5309_4471_abdb_58855cac2a28..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\App.xaml.cs:line 41
2023-08-06 20:33:10,179 [1] FATAL App [(null)] - No app ID argument was supplied. Application will now exit...
2023-08-06 20:33:14,691 [1] ERROR App [(null)] - An error occurred on application startup. "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
System.Windows.Markup.XamlParseException: "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '0.0' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Decimal.Parse(String s)
   at SAM.Core.Extensions.XmlExtensions.GetValueAsDecimal(XmlNode node, String path) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Common\Extensions\XmlExtensions.cs:line 22
   at SAM.Core.SteamUser.RefreshProfile() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 85
   at SAM.Core.SteamUser..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 38
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_b07407ee_8027_43ce_a209_51377c28f325..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\App.xaml.cs:line 41
2023-08-06 20:33:23,425 [1] FATAL App [(null)] - No app ID argument was supplied. Application will now exit...
2023-08-06 20:33:26,888 [1] ERROR App [(null)] - An error occurred on application startup. "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
System.Windows.Markup.XamlParseException: "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '0.0' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Decimal.Parse(String s)
   at SAM.Core.Extensions.XmlExtensions.GetValueAsDecimal(XmlNode node, String path) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Common\Extensions\XmlExtensions.cs:line 22
   at SAM.Core.SteamUser.RefreshProfile() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 85
   at SAM.Core.SteamUser..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 38
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_bc6833b6_6177_4e41_8f08_86e348bde03d..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\App.xaml.cs:line 41
2023-08-06 20:36:25,146 [1] FATAL App [(null)] - No app ID argument was supplied. Application will now exit...
2023-08-06 20:36:29,225 [1] ERROR App [(null)] - An error occurred on application startup. "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
System.Windows.Markup.XamlParseException: "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '0.0' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Decimal.Parse(String s)
   at SAM.Core.Extensions.XmlExtensions.GetValueAsDecimal(XmlNode node, String path) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Common\Extensions\XmlExtensions.cs:line 22
   at SAM.Core.SteamUser.RefreshProfile() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 85
   at SAM.Core.SteamUser..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 38
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_0c85e388_987a_4a3c_a66d_eb93597eef3d..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\App.xaml.cs:line 41
2023-08-06 20:42:20,911 [1] ERROR App [(null)] - An error occurred on application startup. Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.
System.Windows.Markup.XamlParseException: Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '0.0' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Decimal.Parse(String s)
   at SAM.Core.Extensions.XmlExtensions.GetValueAsDecimal(XmlNode node, String path) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Common\Extensions\XmlExtensions.cs:line 18
   at SAM.Core.SteamUser.RefreshProfile() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 85
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_47778512_610e_4856_bbef_f41be0891240..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\App.xaml.cs:line 41
2023-08-06 20:42:24,168 [1] FATAL App [(null)] - No app ID argument was supplied. Application will now exit...
2023-08-06 20:42:27,465 [1] ERROR App [(null)] - An error occurred on application startup. Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.
System.Windows.Markup.XamlParseException: Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '0.0' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Decimal.Parse(String s)
   at SAM.Core.Extensions.XmlExtensions.GetValueAsDecimal(XmlNode node, String path) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Common\Extensions\XmlExtensions.cs:line 18
   at SAM.Core.SteamUser.RefreshProfile() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 85
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_5254eaa7_5cf4_43c7_91d5_e4677c1d2c90..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\App.xaml.cs:line 41
```

</details>
<details>
<summary>log.txt:</summary>

```
2023-08-06 20:32:55,090 [1] INFO  App [(null)] - Application startup.
2023-08-06 20:32:58,091 [1] DEBUG SAMLibraryHelper [(null)] - Skipping app id '13260'.
2023-08-06 20:32:58,804 [1] ERROR App [(null)] - An error occurred on application startup. "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
System.Windows.Markup.XamlParseException: "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '0.0' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Decimal.Parse(String s)
   at SAM.Core.Extensions.XmlExtensions.GetValueAsDecimal(XmlNode node, String path) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Common\Extensions\XmlExtensions.cs:line 22
   at SAM.Core.SteamUser.RefreshProfile() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 85
   at SAM.Core.SteamUser..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 38
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_27ad6281_5309_4471_abdb_58855cac2a28..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\App.xaml.cs:line 41
2023-08-06 20:33:00,880 [6] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '22490' failed.
2023-08-06 20:33:01,321 [6] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '34270' failed.
2023-08-06 20:33:01,936 [6] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '43160' failed.
2023-08-06 20:33:02,982 [6] DEBUG SteamworksManager [(null)] - Skipping GetAppInfo for app id '92500'.
2023-08-06 20:33:10,154 [1] WARN  App [(null)] - The SAM picker process is not running. Starting picker application...
2023-08-06 20:33:10,179 [1] FATAL App [(null)] - No app ID argument was supplied. Application will now exit...
2023-08-06 20:33:10,700 [1] INFO  App [(null)] - Application startup.
2023-08-06 20:33:12,947 [1] DEBUG SAMLibraryHelper [(null)] - Skipping app id '13260'.
2023-08-06 20:33:14,691 [1] ERROR App [(null)] - An error occurred on application startup. "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
System.Windows.Markup.XamlParseException: "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '0.0' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Decimal.Parse(String s)
   at SAM.Core.Extensions.XmlExtensions.GetValueAsDecimal(XmlNode node, String path) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Common\Extensions\XmlExtensions.cs:line 22
   at SAM.Core.SteamUser.RefreshProfile() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 85
   at SAM.Core.SteamUser..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 38
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_b07407ee_8027_43ce_a209_51377c28f325..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\App.xaml.cs:line 41
2023-08-06 20:33:15,673 [6] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '22490' failed.
2023-08-06 20:33:16,085 [6] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '34270' failed.
2023-08-06 20:33:16,619 [6] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '43160' failed.
2023-08-06 20:33:23,396 [1] WARN  App [(null)] - The SAM picker process is not running. Starting picker application...
2023-08-06 20:33:23,425 [1] FATAL App [(null)] - No app ID argument was supplied. Application will now exit...
2023-08-06 20:33:23,960 [1] INFO  App [(null)] - Application startup.
2023-08-06 20:33:26,164 [1] DEBUG SAMLibraryHelper [(null)] - Skipping app id '13260'.
2023-08-06 20:33:26,888 [1] ERROR App [(null)] - An error occurred on application startup. "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
System.Windows.Markup.XamlParseException: "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '0.0' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Decimal.Parse(String s)
   at SAM.Core.Extensions.XmlExtensions.GetValueAsDecimal(XmlNode node, String path) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Common\Extensions\XmlExtensions.cs:line 22
   at SAM.Core.SteamUser.RefreshProfile() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 85
   at SAM.Core.SteamUser..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 38
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_bc6833b6_6177_4e41_8f08_86e348bde03d..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\App.xaml.cs:line 41
2023-08-06 20:36:25,108 [1] WARN  App [(null)] - The SAM picker process is not running. Starting picker application...
2023-08-06 20:36:25,146 [1] FATAL App [(null)] - No app ID argument was supplied. Application will now exit...
2023-08-06 20:36:25,693 [1] INFO  App [(null)] - Application startup.
2023-08-06 20:36:28,526 [1] DEBUG SAMLibraryHelper [(null)] - Skipping app id '13260'.
2023-08-06 20:36:29,225 [1] ERROR App [(null)] - An error occurred on application startup. "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
System.Windows.Markup.XamlParseException: "Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.": номер строки "14" и позиция в строке "14".
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '0.0' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Decimal.Parse(String s)
   at SAM.Core.Extensions.XmlExtensions.GetValueAsDecimal(XmlNode node, String path) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Common\Extensions\XmlExtensions.cs:line 22
   at SAM.Core.SteamUser.RefreshProfile() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 85
   at SAM.Core.SteamUser..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 38
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_0c85e388_987a_4a3c_a66d_eb93597eef3d..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\App.xaml.cs:line 41
2023-08-06 20:36:31,334 [4] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '22490' failed.
2023-08-06 20:36:31,747 [4] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '34270' failed.
2023-08-06 20:36:32,310 [4] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '43160' failed.
2023-08-06 20:36:33,254 [4] DEBUG SteamworksManager [(null)] - Skipping GetAppInfo for app id '92500'.
2023-08-06 20:36:35,172 [4] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '217490' failed.
2023-08-06 20:36:35,864 [4] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '223470' failed.
2023-08-06 20:36:36,744 [4] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '232770' failed.
2023-08-06 20:36:37,456 [4] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '239140' failed.
2023-08-06 20:36:38,159 [4] WARN  SteamworksManager [(null)] - Steam Web API appdetails for app id '246580' failed.
2023-08-06 20:42:17,439 [1] INFO  App [(null)] - Application startup.
2023-08-06 20:42:20,464 [1] DEBUG SAMLibraryHelper [(null)] - Skipping app id '13260'.
2023-08-06 20:42:20,911 [1] ERROR App [(null)] - An error occurred on application startup. Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.
System.Windows.Markup.XamlParseException: Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '0.0' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Decimal.Parse(String s)
   at SAM.Core.Extensions.XmlExtensions.GetValueAsDecimal(XmlNode node, String path) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Common\Extensions\XmlExtensions.cs:line 18
   at SAM.Core.SteamUser.RefreshProfile() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 85
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_47778512_610e_4856_bbef_f41be0891240..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\App.xaml.cs:line 41
2023-08-06 20:42:24,146 [1] WARN  App [(null)] - The SAM picker process is not running. Starting picker application...
2023-08-06 20:42:24,168 [1] FATAL App [(null)] - No app ID argument was supplied. Application will now exit...
2023-08-06 20:42:24,680 [1] INFO  App [(null)] - Application startup.
2023-08-06 20:42:26,893 [1] DEBUG SAMLibraryHelper [(null)] - Skipping app id '13260'.
2023-08-06 20:42:27,465 [1] ERROR App [(null)] - An error occurred on application startup. Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.
System.Windows.Markup.XamlParseException: Предоставление значения для "DevExpress.Mvvm.UI.ViewModelSourceExtension" вызвало исключение.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '0.0' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Decimal.Parse(String s)
   at SAM.Core.Extensions.XmlExtensions.GetValueAsDecimal(XmlNode node, String path) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Common\Extensions\XmlExtensions.cs:line 18
   at SAM.Core.SteamUser.RefreshProfile() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 85
   at lambda_method3(Closure)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create[T](Expression`1 constructorExpression)
   at SAM.Core.SteamUser.Create() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM.Core\Models\SteamUser.cs:line 43
   at SAM.ViewModels.MainWindowViewModel..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\ViewModels\MainWindowViewModel.cs:line 14
   at SAM.ViewModels.MainWindowViewModel_5254eaa7_5cf4_43c7_91d5_e4677c1d2c90..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DevExpress.Mvvm.POCO.ViewModelSource.Create(Type type)
   at DevExpress.Mvvm.Native.ViewModelSourceHelper.Create(Type type)
   at DevExpress.Mvvm.UI.ViewModelSourceExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SAM.MainWindow.InitializeComponent() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml:line 1
   at SAM.MainWindow..ctor() in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\MainWindow.xaml.cs:line 7
   at SAM.App.OnStartup(StartupEventArgs args) in D:\a\SteamAchievementManager\SteamAchievementManager\SAM\App.xaml.cs:line 41
   
```

**Comment by syntax-tm** [comment]
So that looks like a different error. Specifically one when parsing `"0.0"` to decimal. I'm going to guess this is due to locale because in the US the `.` is the decimal placeholder but in your locale I'm pretty sure that is the `,` symbol.

I made some changes to the `XmlExtensions` class that should handle non-US globalization more gracefully.

**Comment by syntax-tm** [comment]
It's from the `ru-RU` culture so the changes made should resolve it since it will try (and fail) the current locale (`ru-RU`), then `en-US` (which will work), before as a last resort using `InvariantCulture`.
